# Generated by Django 6.0.6 on 2026-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
