# Generated by Django 6.0.6 on 2026-06-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_author_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
