# Generated by Django 6.0.6 on 2026-06-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_add_slug_to_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
