# Generated by Django 6.0.6 on 2026-06-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='source_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
